CREATE TABLE IF NOT EXISTS preference_items(
    id bigint AUTO_INCREMENT NOT NULL primary key,
    item varchar(50) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);